---
- hosts: centos_7
  vars:
    - test_password: '$1$RuDdxEJa$N1Uo2JgInhCkjvgNDKEYx.'
  become: yes
  tasks:
  - name: Add user test
    user:
      name=test
      password={{ test_password }}

  - name: Add user remote to sudoers
    lineinfile:
      "dest=/etc/sudoers
      regexp='^test ALL'
      line='test ALL=(ALL) NOPASSWD: ALL'
      state=present"
