---
- hosts: ubuntu_14
  vars:
    - test_password: '$1$5wM8e74A$S29Z4abwsD/cp5bEusL8c.'
  become: yes
  tasks:
  - name: Add user masterkey
    user:
      name=masterkey
      password={{ test_password }}

  - name: Add user remote to sudoers
    lineinfile:
      "dest=/etc/sudoers
      regexp='^masterkey ALL'
      line='masterkey ALL=(ALL) NOPASSWD: ALL'
      state=present"
